alias profile='source ~/.bashrc && echo "Profile Reloaded!"'
alias origin='git push origin main'
alias olympus='ssh bgorgani@olympus.srv.prnynj.alticeusa.net'
alias pulsar='ssh -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 -oHostKeyAlgorithms=+ssh-dss bgorgani@pulsar2.suddenlink.net'
alias live='git push live main'
alias sas='cd ~/Git/SASN_Admin && activate'
alias collectstatic='python manage.py collectstatic'
alias makemigrations='python manage.py makemigrations'
alias migrate='python manage.py migrate'
alias runserver='python manage.py runserver'
alias activate='source ./venv/bin/activate'
alias arrislc='cd ~/git/arris-lc-failover && activate'
alias nvim-config='cd ~/.config/nvim && nvim .'
alias tmux-config='nvim ~/.tmux.conf'
alias tm='tmux new -A -s Main'
alias tkill='tmux kill-server'
alias tsave='~/tmux-session save'
alias trestore='~/tmux-session restore && tmux a'
alias nv='nvim .'
alias cat='bat --color=always'
alias fz='fzf -m --preview "bat --show-all --color=always --line-range=:500 {}"'
alias fnv='fz --bind "enter:become(nvim {})"'
alias fcd='`__fzf_cd__`'
alias fb='bat $(fz)'
alias pgl="git log --color=always --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)'"
alias pggl="pgl --graph"
